# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: s1WLsnELRaiWD7Lf+MkDC1cer6iEs/yqc5IfiUtcaueLxdHdIMbC4ZPm7lfFc5idWK6fZoBkett4fO/8NI2BAqJjtUycMLDWNfFzux6KcnscR/GVtLe5v969oo8QPVy69X+uWEo3liVymTPUKz4jDjGRIuOEQ7ML5dAoBMvBdBUZyKvBhCKladZVqpMec6zzBrOQxrTECWa7wveupZxxD9rtwM5FP2vRFoAw6V6nKrPsI1I6aO2znelNpTyHOCJaZ0pvnSxgW2ZJkwozYAz8vUohGe+LiNnFWSeyqFqNZsibLqV0e9Mj122lvbgLpK2M4fcDVA63ORGEfOKO02qsHJnx9ZxRVT+J4qNQ6YKcocpEd3bKsRvSglUfdZSSJaXyvOSY2uxgQVTOszAQCIkaihNRDMD7oXPSskGoYPQB/2dYgkZqWR8r5KPx8Oh2MfU69Gbl1p5KWBrLpJUcwx8yCNxkrxCJFlHjUbLZa5Z0LGpRQ1JvCtI5EPBdiyT+6uhR/MHjwx7u3+bPZ+W8PtyeMwTujo9RCjQAjCqhTQU9egnt5RfPEMgiYl39142+xl4HR1WKNLM0okrkcZ6Z0MRsWxTot1dKl+DDBzqv1de/6Rd0nIKKNCDWH2ro1lUJxvf+gIsWqDPDmlEkgEr/YqO6Ofpp2iksIAv8dA3qUuUF0co=
  file: dr4pl_*.tar.gz
  on:
    repo: aubreybailey/dr4pl
    tags: true
    branch: releases
